sequenceDiagram
    participant browser
    participant server

    Note right of browser: Browser executes the Javascript to add the new note to the screen

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa

    activate server
    server-->>browser: HTTP 201: Created
    deactivate server

    Note right of browser: Browser logs response text to console